-- NORTHSTAR metric contract (DuckDB / PostgreSQL-style SQL).
-- Input: data/cohort.csv generated by scripts/build_demo_data.py.
-- The demo events and telemetry aggregates are synthetic, not company results.

WITH cohort AS (
    SELECT
        week,
        label AS week_start,
        queue,
        CAST(volume AS BIGINT) AS conversations,
        CAST(resolution AS DOUBLE) / 100.0 AS ai_resolution_rate,
        CAST(grounded AS DOUBLE) / 100.0 AS grounded_answer_rate,
        CAST(handoff AS DOUBLE) / 100.0 AS human_handoff_rate,
        CAST(latency AS DOUBLE) AS p95_latency_seconds,
        CAST(modelCost AS DOUBLE) AS model_cost_per_conversation
    FROM read_csv_auto('data/cohort.csv')
),
weekly AS (
    SELECT
        week,
        week_start,
        SUM(conversations) AS conversations,
        SUM(conversations * ai_resolution_rate) / SUM(conversations) AS ai_resolution_rate,
        SUM(conversations * grounded_answer_rate) / SUM(conversations) AS grounded_answer_rate,
        SUM(conversations * human_handoff_rate) / SUM(conversations) AS human_handoff_rate,
        SUM(conversations * p95_latency_seconds) / SUM(conversations) AS p95_latency_seconds,
        SUM(conversations * model_cost_per_conversation) / SUM(conversations) AS model_cost_per_conversation
    FROM cohort
    GROUP BY week, week_start
)
SELECT
    *,
    CASE
        WHEN grounded_answer_rate >= 0.90
         AND human_handoff_rate <= 0.35
         AND p95_latency_seconds <= 2.00
        THEN 'READY_TO_SCALE'
        ELSE 'HOLD_RELEASE'
    END AS release_gate
FROM weekly
ORDER BY week;
